### PR TITLE
Reuse metanorma-linux-setup script

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/metanorma-document-gh-pages/issues/2

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse there is no `deploy_key` in this repo, should them be here?

**Comment by ronaldtse** [comment]
@CAMOBAP795 no, this repo is only to teach the user how to use the framework, there is nothing to deploy here.

**Comment by CAMOBAP** [comment]
@ronaldtse  Should we remove deploy script from it?

**Comment by ronaldtse** [comment]
Nah, the deploy script is put here so others can download to use it. I think we really need a "template" directory that people can do `metanorma new` and it automatically creates a template directory for them that includes these files.

**Comment by CAMOBAP** [comment]
@ronaldtse ready for review and merge

**Pull request merged**
